name: Get GitHub App Token

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate GitHub App Token
        run: |
          printf "%s" "${{ secrets.GH_APP_PRIVATE_KEY }}" > private-key.pem
          chmod 600 private-key.pem
          chmod +x .bin/get-github-app-token.sh
          TOKEN=$(bash .bin/get-github-app-token.sh)
          echo "COMPOSER_TOKEN=$TOKEN" >> $GITHUB_ENV

      - name: Install Composer Dependencies
        run: composer install --no-interaction --prefer-dist
