name: Generate GitHub App Token

on:
  workflow_dispatch:

jobs:
  generate-token:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Write GitHub App Private Key to File
        run: |
          echo "${{ secrets.GH_APP_PRIVATE_KEY }}" > private-key.pem
          chmod 600 private-key.pem
          # Verify the private key format
          if ! grep -q "BEGIN RSA PRIVATE KEY" private-key.pem; then
            echo "::error::Private key does not appear to be in valid PEM format"
            exit 1
          fi

      - name: Generate GitHub App Token
        id: generate_token
        run: |
          # Make script executable
          chmod +x .bin/get-github-app-token.sh
          
          echo "Executing token generation script..."
          
          # Capture only the token (not debug output)
          TOKEN=$(.bin/get-github-app-token.sh private-key.pem)
          
          # Check if token was actually generated
          if [[ -z "$TOKEN" ]]; then
            echo "::error::Generated token is empty"
            exit 1
          fi
          
          # Store token securely as output and env var
          echo "token=$TOKEN" >> "$GITHUB_OUTPUT"
          {
            echo "GITHUB_TOKEN<<EOF"
            echo "$TOKEN"
            echo "EOF"
          } >> "$GITHUB_ENV"
          
          echo "Token generated successfully"
          
      # Test the token works
      - name: Use the token
        run: |
          # Test token with API call
          response=$(curl -s \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/installation/repositories)
            
          # Show repo count (safe to display)
          echo "Token can access $(echo "$response" | jq '.total_count') repositories"
  