- name: Generate GitHub App Token
  run: |
    printf "%s" "${{ secrets.GH_APP_PRIVATE_KEY }}" > private-key.pem
    chmod 600 private-key.pem
    TOKEN=$(bash .bin/get-github-app-token.sh)
    echo "COMPOSER_TOKEN=$TOKEN" >> $GITHUB_ENV
